name: windows
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: windows-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: start pqsql
        run: |
          $postgreSqlSvc = Get-Service "postgresql*" 
          Set-Service $postgreSqlSvc.Name -StartupType manual 
          $postgreSqlSvc.Start() 
          try {
            (Get-Service "postgresql*").Start()
          } catch  {
            $_ | select *
          }
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: curl -L https://cpanmin.us | perl - --installdeps .
      - name: Run Tests
        run: prove -l
        env: 
          TEST_ONLINE: postgresql://postgres:root@localhost/postgres
